org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

moddev_gradle_version=2.0.78
minecraft_version=1.21.1
neoforge_version=21.1.133

mod_id=livingcities
mod_name=Living Cities
mod_version=0.1.0-alpha.1
mod_group=com.branciho.livingcities
mod_license=MIT
mod_authors=bcoros, OpenAI ChatGPT
mod_description=Turn any custom-built Minecraft city into a functional living city simulation.
